<?php
	include_once( "pdfc.inc.php" );
	
	class holidaysPDF extends PDFC
	{
		
		function holidaysPDF( $orientation )
		{
			PDFC::PDFC( $orientation );
		}
		
		function PrintReport( $nYear )
		{
			$nCellSizeX = 7;
			$nCellSizeY = 4;
			
			$sInfo = $_SESSION['calendar_pdf'];
			unset( $_SESSION['calendar_pdf'] );
			
			//Get Info
			$aInfo = array();
			$aElements = array();
			$aData = array();
			
			$aInfo = explode( "|", $sInfo );
			foreach( $aInfo as $sElements )
			{
				$aElements = explode( ",", $sElements );
				
				if( isset( $aElements[0] ) && isset( $aElements[1] ) && isset( $aElements[2] ) && isset( $aElements[3] ) )
				{
					$aData[$aElements[0] . "-" . $aElements[1]]['type'] = $aElements[3];
					$aData[$aElements[0] . "-" . $aElements[1]]['year'] = $aElements[2];
				}
			}
			//End Get Info
			
			$this->AddPage( 'L' );
			
			$this->Image( $_SESSION['BASE_DIR'] . '/images/title.png', 50, 10, 200 );
			
			$this->Ln( 5 );
			
			$this->SetFont( 'FreeSans', '', 18 );
			$this->SetXY( 0, 45 );
			$this->Cell( 297, 10, "ПРАЗНИЧНИ / РАБОТНИ ДНИ", 0, 1, "C" );
			
			$this->Ln( 12 );
			
			$nLocationX = 40;
			$nLocationY = 65;
			for( $nIteration = 1; $nIteration <= 12; $nIteration++ )
			{
				$this->printMonth( $nLocationX, $nLocationY, $nIteration, $nYear, $nCellSizeX, $nCellSizeY, $aData );
				
				$nLocationX += ( $nCellSizeX * 8 );
				if( $nIteration == 4 || $nIteration == 8 )
				{
					$nLocationX = 40;
					$nLocationY += ( $nCellSizeY * 9 );
				}
			}
			
			$this->SetAuthor( "TELENET" );
			$this->SetCreator( "Generated By Telenet" );
			$this->SetDisplayMode( 'real' );
			$this->Output();
		}
		
		private function printMonth( $nLocX, $nLocY, $nMonth, $nYear, $nCellSizeX = 10, $nCellSizeY = 5, $aData )
		{
			$oDBHolidays = new DBHolidays();
			
			$nDaysInMonth = date( "t", mktime( 0, 0, 0, $nMonth, 1, $nYear ) );
			$aDays = array( 0 => "Пн", 1 => "Вт", 2 => "Ср", 3 => "Чт", 4 => "Пт", 5 => "Сб", 6 => "Нд" );
			$aMonths = array(
				1 	=> "Януари",
				2 	=> "Февруари",
				3 	=> "Март",
				4 	=> "Април",
				5 	=> "Май",
				6 	=> "Юни",
				7 	=> "Юли",
				8 	=> "Август",
				9 	=> "Септември",
				10 	=> "Октомври",
				11 	=> "Ноември",
				12 	=> "Декември",
			);
			
			//Captions
			$this->setFillColor( 255, 238, 0 );
			$this->SetFont( 'FreeSans', '', 9 );
			$this->SetXY( $nLocX, $nLocY );
			$this->Cell( ( $nCellSizeX * 7 ), $nCellSizeY, $aMonths[$nMonth] . " " . $nYear . " : " . $oDBHolidays->getWorkdaysForMonth( $nYear, $nMonth ), 1, 0, "C", 1 );
			
			$nLocY += $nCellSizeY;
			
			$this->SetFont( 'FreeSans', 'B', 8 );
			
			for( $i = 0; $i <= 6; $i++ )
			{
				if( $i <= 4 ) $this->setFillColor( 255, 255, 170 );
				else $this->setFillColor( 255, 170, 170 );
				
				$nCellX = $nLocX + ( $i * $nCellSizeX );
				
				$this->SetXY( $nCellX, $nLocY );
				$this->Cell( $nCellSizeX, $nCellSizeY, $aDays[$i], 1, 0, "C", 1 );
			}
			$nLocY += $nCellSizeY;
			//End Captions
			
			//Calendar Days
			$nNextRow = 6;
			$bNextRowChanged = false;
			
			$this->SetFont( 'FreeSans', '', 8 );
			for( $nDay = 1; $nDay <= $nDaysInMonth; $nDay++ )
			{
				$nWeekday = date( "w", mktime( 0, 0, 0, $nMonth, $nDay, $nYear ) );
				$nWeekday--; if( $nWeekday < 0 )$nWeekday = 6;
				
				if( $nWeekday <= 4 ) $this->setFillColor( 255, 255, 221 );
				else $this->setFillColor( 255, 221, 221 );
				
				//Modify By Records
				if( isset( $aData[$nDay . "-" . $nMonth] ) )
				{
					$sLogType = isset( $aData[$nDay . "-" . $nMonth]['type'] ) ? $aData[$nDay . "-" . $nMonth]['type'] : "";
					$nLogYear = isset( $aData[$nDay . "-" . $nMonth]['year'] ) ? $aData[$nDay . "-" . $nMonth]['year'] : "N/A";
					
					if( !empty( $sLogType ) && $nLogYear != "N/A" )
					{
						if( $sLogType == "holiday" ) $this->setFillColor( 255, 102, 119 );
						else if( $nYear == $nLogYear )
						{
							if( $sLogType == "workday" ) $this->setFillColor( 255, 255, 221 );
							if( $sLogType == "restday" ) $this->setFillColor( 255, 221, 221 );
						}
					}
				}
				//End Modift By Records
				
				if( !$bNextRowChanged ) { $nNextRow = 8 - $nWeekday; $bNextRowChanged = true; }
				
				$nCellX = $nLocX + ( $nWeekday * $nCellSizeX );
				if( $nDay == $nNextRow )
				{
					$nNextRow += 7;
					$nLocY += $nCellSizeY;
				}
				
				$this->SetXY( $nCellX, $nLocY );
				$this->Cell( $nCellSizeX, $nCellSizeY, $nDay, 1, 0, "C", 1 );
			}
			//End Calendar Days
		}
	}
?>