#!/bin/sh
echo -n 'Perl WebSocket server '

case "$1" in
start)  if [ -f /var/run/wss.pid ]; then
                printf ' is running! %s\n'
        else
                printf ' is starting now! %s\n'
                /www/telenet/canvas/demons/wss.pl
                pid=`cat /var/run/wss.pid`
                echo 'PID ' ${pid}
        fi
        ;;
restart) if [ -f /var/run/wss.pid ]; then
                kill `cat /var/run/wss.pid`
                printf ' is anihilated! %s\n'
                pid=`cat /var/run/wss.pid`
                echo 'PID ' ${pid}
                rm /var/run/wss.pid
                printf 'and now starting! %s\n'
                /www/telenet/canvas/demons/wss.pl
                pid=`cat /var/run/wss.pid`
                echo 'PID ' ${pid}
        else
                printf ' is starting now! %s\n'
                /www/telenet/canvas/demons/wss.pl
                pid=`cat /var/run/wss.pid`
                echo 'PID ' ${pid}
        fi
        ;;
stop)
        if [ -f /var/run/wss.pid ]; then
                kill `cat /var/run/wss.pid`
                printf ' is anihilated! %s\n'
                pid=`cat /var/run/wss.pid`
                echo 'PID ' ${pid}
                rm /var/run/wss.pid
        else
                printf ' is not running! %s\n'
        fi
        ;;
*)
        echo "Usage: `basename $0` {start|stop|restart}" >&2
        exit 64
        ;;
esac

exit 0


