#!/bin/bash
echo -n 'Monitoring Demon Server '
CURRENT=$PWD
BASEDIR=$(dirname $0)
cd $BASEDIR
case "$1" in
start)  if [ -f monitoring_daemon.pid ]; then
                printf ' is running! %s\n'
        else
                php < monitoring_daemon.php > monitoring_daemon.log 2>&1 &
                sleep 1
                printf ' is starting now with PID  %s\n' `cat monitoring_daemon.pid`
        fi
        ;;
restart) if [ -f monitoring_daemon.pid ]; then
                pid=`cat monitoring_daemon.pid`
                kill ${pid}
                printf ' with PID %s is anihilated.' ${pid}
                rm monitoring_daemon.pid
                php < monitoring_daemon.php > monitoring_daemon.log 2>&1 &
                sleep 1
                printf '.'
                sleep 1
                printf '. and now started with PID %s\n' `cat monitoring_daemon.pid`
        else
                php < monitoring_daemon.php > monitoring_daemon.log 2>&1 &
                sleep 1
                printf ' is starting now with PID %s\n' `cat monitoring_daemon.pid`
        fi
        ;;
stop)
        if [ -f monitoring_daemon.pid ]; then
                pid=`cat monitoring_daemon.pid`
                kill ${pid}
                printf ' is anihilated PID %s\n' ${pid}
                rm monitoring_daemon.pid
        else
                printf ' is not running! %s\n'
        fi
        ;;
state)  if [ -f monitoring_daemon.pid ]; then
                printf ' is probably running. %s\n'
        fi
        ;;
*)
        echo "Usage: `basename $0` {start|stop|restart|state}" >&2
        exit 64
        ;;
esac
cd $CURRENT
exit 0

